/*
* 事件枚举
* 将需要通知的事件key保存为枚举类型
*/

enum EventDef
{
    EVET_FIRE = 0,
    EVENT_CROUCH = 1,
    EVENT_HIT_ENERMY = 2,
    // EVENT_DETECTED_ENERMY = 3,
    // EVENT_UNDETECTED_ENERMY = 4,
    EVENT_START_FIRE = 5,
    EVEMT_STOP_FIRE = 6,
    EVENT_CHANGE_CAMERA_MODE = 7,
    EVENT_ROTATE_CAMERA_FREE = 9,
    EVENT_CHARACTER_MOVE = 10,
    EVENT_RIGHT_SCREEN_TOUCH = 11,
    EVENT_JOY_STICK_TOUCH = 12,
    EVENT_AIM_CLICK = 13,
    EVENT_AIM_STATE_CHANGE = 14,
    EVENT_ROOM_LIST_CHANGE = 15,
    EVENT_JOIN_ROOM = 16,
    EVENT_UPDATE_ROOM = 17,
    EVENT_CAMERA_LATE_UPDATE = 18,
    EVENT_CLIENT_STATE = 19,
    EVENT_KILLING_INFO = 20,
}


